Second
Preisy/labs2Semester pull request #2
Opened 2022-03-09 23:11 UTC by Preisy

Исправил toSet, добавил map, добавил copyDynamicArray, изменил removeElementByIndex, прописал тесты и вроде все. В файле test1.c решил оставить цикл заполнения associativeArray, а также его вывод, потому что другой нормальной реализации не придумал. 
Долго копался с гитом, намракобесничал немного, пару тестовых коммитов запушил в обе ветки.

2022-03-10 00:12 UTC, Preisy commented
Я забыл добавить .idea в .gitignore, прошу прощения

2022-03-12 13:29 UTC, SorokinIA commented
у тебя конфликт (

2022-03-12 19:01 UTC, SorokinIA requested changes

2022-03-12 19:01 UTC, SorokinIA commented on lab_1/src/DynamicArray.c
> +    if (dynamicArray->length < dynamicArray->bufLength * 1/3 && dynamicArray->bufLength / 2 >= 10) {
а зачем тут удалять что то?

2022-03-12 19:14 UTC, Preisy commented on lab_1/src/DynamicArray.c
>  void toSet(Info* info, struct DynamicArray* dynamicArray, struct DynamicArray* exceptions) {
exceptions - массив исключений, то есть тех элементов, которых не должно быть в результирующем массиве. toSet() удаляет елементы в dynamicArray, если они встречаются в exceptions, а также, если они повторяются. То есть на выходе получается массив уникальных элементов. exceptions может быть пустой

2022-03-12 19:15 UTC, Preisy commented on lab_1/src/DynamicArray.c
> +    if (dynamicArray->length < dynamicArray->bufLength * 1/3 && dynamicArray->bufLength / 2 >= 10) {
ну просто память высвободить. если мы слишком много всего удалили, зачем нам куча неиспользуемой памяти. Рословцев посоветовал сокращать массив вдвое, если элементов меньше 1/3, отсюда и цифры.

2022-03-12 19:17 UTC, SorokinIA commented on lab_1/src/DynamicArray.c
> +    if (dynamicArray->length < dynamicArray->bufLength * 1/3 && dynamicArray->bufLength / 2 >= 10) {
не не не. Нужно сократить сократишь руками.  у тебя для этого метод на обрезание должен быть

2022-03-12 19:18 UTC, SorokinIA commented on lab_1/src/DynamicArray.c
>  void toSet(Info* info, struct DynamicArray* dynamicArray, struct DynamicArray* exceptions) {
не эффективная штука какая то, тут нужно другой подход использовать, но если просили такую сделать, наверное ок.

2022-03-12 19:37 UTC, closed without merging